create table infection_records (id bigint generated by default as identity, flag boolean not null, survivor_id bigint not null, times_reported integer not null, primary key (id))
create table inventory (id bigint generated by default as identity, ammunition boolean not null, food boolean not null, medication boolean not null, water boolean not null, survivor_id bigint, primary key (id))
create table survivor (id bigint generated by default as identity, age integer not null, gender varchar(255), location varchar(255), name varchar(255), primary key (id))
alter table inventory add constraint FKt8d7qn583wsuio8he4joq3kmp foreign key (survivor_id) references survivor
